### ISSUE TITLE
Issue bypassing a video

### ISSUE THREAD

**Issue by keaarori** [AlessandroFC15/Fuck-Youtube#38]
Trying to open - https://www.youtube.com/watch?v=5F4dpn8xJvQ in US opens and attempts to bypass and loads your player without any video being pushed. This video will work correctly using a VPN instead.

**Comment by AlessandroFC15** [comment]
Hello, @keaarori.

I've made some changes and I think this bug might be fixed. Can you give a try? In order for you to update your extension, please follow the steps below:

- Uninstall the current version you have.
- Download the .crx file of the new release developed specifically for this issue (0.0.0.5). You can download from this link: https://github.com/AlessandroFC15/Fuck-Youtube/blob/master/releases/0.0.0.5/release_0.0.0.5.crx
- Open the extensions page of Chrome (enter chrome://extensions as the url)
- Drag and drop the downloaded file into the extensions page
- Install :)

Let me know if the problem is fixed.

Thanks :)

**Comment by JustSch** [comment]
It also doesn't seem to work with this video https://www.youtube.com/watch?v=Y6N7A4lkwH0

**Comment by AlessandroFC15** [comment]
@JustSch You are right, Justin, it is not working. According to some research, this specific video is only available in Japan and Somaliland. 

Unfortunately, we don't have proxies in those countries and also we don't have enough resources to make that happen. If anyone finds a realiable proxy in Japan, I can include as another source to look for mirrors. But for now, there's not much we can do about that :(

**Comment by keaarori** [comment]
Looks like that fixed it, thank you.

**Comment by keaarori** [comment]
Seems like youtube really does not want you to do this, editing the manifest manually to something else and installing it seems to work around it.

**Comment by AlessandroFC15** [comment]
Well, I'm glad your problem is fixed :)
